<a href="https://colab.research.google.com/github/enesergen/ML-Fundamentals/blob/main/ML_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#import pandas lib
import pandas as pd
#dataset url
url="https://raw.githubusercontent.com/tansutosun/MachineLearning/main/organics.csv";
#read dataset from github csv
df=pd.read_csv(url)

In [3]:
#viewing dataset values with columns
df

,ID,DemAffl,Dem Age,DemCluster,DemClusterGroup,DemGender,DemReg,DemTVReg,PromClass,PromSpend,PromTime,TargetBuy,Target Amt
0,140,10.0,76.0,16.0,C,U,Midlands,Wales & West,Gold,16000.00,4.0,0,0
1,620,4.0,49.0,35.0,D,U,Midlands,Wales & West,Gold,6000.00,5.0,0,0
2,868,5.0,70.0,27.0,D,F,Midlands,Wales & West,Silver,0.02,8.0,1,1
3,1120,10.0,65.0,51.0,F,M,Midlands,Midlands,Tin,0.01,7.0,1,1
4,2313,11.0,68.0,4.0,A,F,Midlands,Midlands,Tin,0.01,8.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22218,52834058,13.0,65.0,9.0,B,F,South East,London,Silver,1500.00,5.0,0,0
22219,52834376,15.0,73.0,34.0,D,U,South East,S & S East,Gold,6053.06,12.0,0,0
22220,52837057,9.0,70.0,15.0,B,F,North,Yorkshire,Gold,6000.00,5.0,0,0
22221,52838096,11.0,66.0,8.0,B,F,North,N West,Silver,5000.00,5.0,0,0
22222,52856469,3.0,75.0,53.0,F,NaN,South West,S West,Gold,6000.00,2.0,0,0

In [4]:
#check column names
df.keys()

Index(['ID', 'DemAffl', 'Dem Age', 'DemCluster', 'DemClusterGroup',
       'DemGender', 'DemReg', 'DemTVReg', 'PromClass', 'PromSpend', 'PromTime',
       'TargetBuy', 'Target Amt'],
      dtype='object')

In [9]:
#Deleting ID Column
deleting_column_name='ID'
if deleting_column_name in df.keys():
  del df[deleting_column_name]

In [11]:
#reviewing the current state
df.keys()

Index(['DemAffl', 'Dem Age', 'DemCluster', 'DemClusterGroup', 'DemGender',
       'DemReg', 'DemTVReg', 'PromClass', 'PromSpend', 'PromTime', 'TargetBuy',
       'Target Amt'],
      dtype='object')

In [12]:
#Check outliers data
df.isnull().sum()

DemAffl            1085
Dem Age            1508
DemCluster          674
DemClusterGroup     674
DemGender          2512
DemReg              465
DemTVReg            465
PromClass             0
PromSpend             0
PromTime            281
TargetBuy             0
Target Amt            0
dtype: int64

In [19]:
#Writing data type of  data frame columns
for data_type in df.keys():
  print(data_type+":"+str(df[data_type].dtypes))

DemAffl:float64
Dem Age:float64
DemCluster:float64
DemClusterGroup:object
DemGender:object
DemReg:object
DemTVReg:object
PromClass:object
PromSpend:float64
PromTime:float64
TargetBuy:int64
Target Amt:int64

In [22]:
#Writing numeric column type
for column_name in df.keys():
  if pd.api.types.is_numeric_dtype(df[column_name]):
    print(column_name +" is numeric")
  else:
    print(column_name+" is not numeric")

DemAffl is numeric
Dem Age is numeric
DemCluster is numeric
DemClusterGroup is not numeric
DemGender is not numeric
DemReg is not numeric
DemTVReg is not numeric
PromClass is not numeric
PromSpend is numeric
PromTime is numeric
TargetBuy is numeric
Target Amt is numeric

In [41]:
#Defining function for adjusting outliers data
def fillOutliersData(data_frame):
  #column key list
  column_list=data_frame.keys()

  for column_name in column_list:
    #if numeric, replace with median value for this column
    if pd.api.types.is_numeric_dtype(data_frame[column_name]):
      data_frame[column_name].fillna(data_frame[column_name].median(),inplace=True)
    #if not numeric, replace with mod value
    else:
      data_frame[column_name].fillna(data_frame[column_name].mode()[0],inplace=True)

  return data_frame

In [43]:
#call function
df=fillOutliersData(df)

#check null values
df.isnull().sum()

DemAffl            0
Dem Age            0
DemCluster         0
DemClusterGroup    0
DemGender          0
DemReg             0
DemTVReg           0
PromClass          0
PromSpend          0
PromTime           0
TargetBuy          0
Target Amt         0
dtype: int64